services:
  backend:
    environment:
      ENVIRONMENT: production
 
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile.prod
    environment:
      FRONTEND_SERVER_NAME: localhost
